yaml:
	python main.py --yaml_to_json go-vise.bluto.yaml output.json --schema schema.yaml
json:
	python main.py --json_to_yaml output.json output.yaml --schema schema.yaml
validate:
	python main.py --validate output.json schema.yaml
