yaml:
	python main.py --yaml-to-json go-vise.bluto.yaml output.json --schema schema.json
json:
	python main.py --json-to-yaml output.json output.yaml --schema schema.json
validate:
	python main.py --validate output.json schema.json
